# Generated by Django 5.1.3 on 2024-12-01 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineAlliances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airlinealliances')),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200)),
                ('airports', models.ManyToManyField(to='api.airports')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_flights', to='api.airlines')),
                ('from_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from_flights', to='api.destinations')),
                ('to_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_flights', to='api.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flights', models.ManyToManyField(to='api.flights')),
            ],
        ),
    ]
